### ISSUE TITLE
感谢与咨询

### ISSUE THREAD

**Issue by carreyda** [5ime/API-Docs#1]
非常感谢作者提供的免费好用的接口🥰🥰🥰

现在有两个问题咨询一下

1.获取天气的接口大概什么时候可以更新完成？

2.bilibili接口是不再更新了吗
![WheslbIzxw1FQjFz#rRFoQ==](https://github.com/5ime/API-Docs/assets/55567122/e03eaf5a-f982-4daf-8c9c-855d66e284f1)

**Comment by 5ime** [comment]
天气接口暂时未找到好的上有接口，推荐使用心知天气的吧~
bilibili的话是有啥需求吗？有需求的话可以加一下

**Comment by carreyda** [comment]
非常感谢，bilibili也没有特殊的需求，当然有是最好的了🥰
![rrOcSzeh#Mlr79Hu3LkhIg==](https://github.com/5ime/API-Docs/assets/55567122/72bfdfa0-5c3c-43d0-8c51-b98fcae34738)
只不过是现在这个url是null

**Comment by 5ime** [comment]
感谢提醒~ 已修复
