### ISSUE TITLE
请求异常

### ISSUE THREAD

**Issue by carreyda** [5ime/API-Docs#6]
好多接口请求异常啦
随机一言、ip图片等

**Comment by carreyda** [comment]
https://tenapi.cn/  这个也进不去啦

**Comment by 5ime** [comment]
貌似 `湖北` 地区节点出问题了
![image](https://github.com/5ime/API-Docs/assets/31686695/052b7c89-1935-4ea4-bead-80e11c766c2e)

**Comment by carreyda** [comment]
那这个有计划恢复嘛☺️

**Comment by 5ime** [comment]
> 那这个有计划恢复嘛☺️

网络节点波动很正常，会自行恢复，目前应该无问题。
